# Production override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  app:
    build:
      target: production
    container_name: car-management-app-prod
    volumes:
      # Remove development volume mount
      - /var/www
      # Add production optimized volume for static assets only
      - app_public:/var/www/public
    environment:
      - APP_ENV=production
      - APP_DEBUG=false

  nginx:
    container_name: car-management-nginx-prod
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      # Use shared volume for static assets in production
      - app_public:/var/www/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Uncomment below for SSL certificates
      # - ./docker/nginx/ssl:/etc/nginx/ssl

  database:
    container_name: car-management-db-prod
    ports:
      # Don't expose database port in production
      - "127.0.0.1:${DB_PORT:-3306}:3306"

  redis:
    container_name: car-management-redis-prod
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    ports:
      # Don't expose Redis port in production
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"

  adminer:
    # Remove adminer in production for security
    deploy:
      replicas: 0

volumes:
  app_public:
    driver: local
