# version attribute is obsolete in newer Docker Compose

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        container_name: car-management-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/php-dev.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            - APP_ENV=${APP_ENV:-local}
            - APP_DEBUG=${APP_DEBUG:-true}
            - DB_HOST=${DB_HOST:-database}
            - DB_DATABASE=${DB_DATABASE:-car_management}
            - DB_USERNAME=${DB_USERNAME:-car_user}
            - DB_PASSWORD=${DB_PASSWORD:-car_password}
            - REDIS_HOST=${REDIS_HOST:-redis}
            - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
        depends_on:
            - database
            - redis
        networks:
            - car-management

    nginx:
        image: nginx:alpine
        container_name: car-management-nginx
        restart: unless-stopped
        ports:
            - "${NGINX_PORT:-8080}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - car-management

    database:
        image: mariadb:10.11
        container_name: car-management-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
            MYSQL_DATABASE: ${DB_DATABASE:-car_management}
            MYSQL_USER: ${DB_USERNAME:-car_user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-car_password}
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/custom.cnf
        ports:
            - "${DB_PORT:-3307}:3306"
        networks:
            - car-management

    redis:
        image: redis:7-alpine
        container_name: car-management-redis
        restart: unless-stopped
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - redis_data:/data
        networks:
            - car-management

    adminer:
        image: adminer
        container_name: car-management-adminer
        restart: unless-stopped
        ports:
            - "${ADMINER_PORT:-8081}:8080"
        depends_on:
            - database
        networks:
            - car-management

volumes:
    db_data:
        driver: local
    redis_data:
        driver: local

networks:
    car-management:
        driver: bridge
